os:
  - linux
  - osx

dist: trusty
language: node_js

node_js:
  - '9'
  - '8'
  - '10'

sudo: required

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -screen 1 800x600x8 > /dev/null 2>&1 &
  - npm install
